name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          ffmpeg \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev \
          libgstreamer1.0 \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good

    - name: Install Java 8 (Required for older Android builds)
      run: |
        sudo apt-get install -y openjdk-8-jdk
        sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
        export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
        echo "JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" >> $GITHUB_ENV

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer==1.2.0
        pip install cython==0.29.21

    - name: Cache Buildozer global directory
      uses: actions/cache@v3
      with:
        path: .buildozer_global
        key: buildozer-global-${{ hashFiles('buildozer.spec') }}

    - name: Cache Buildozer directory  
      uses: actions/cache@v3
      with:
        path: .buildozer
        key: buildozer-${{ hashFiles('buildozer.spec', '**/*.py') }}

    - name: Build with Buildozer (Let it handle Android SDK)
      run: |
        buildozer android debug
      env:
        JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64

    - name: List build output
      run: |
        echo "Contents of bin directory:"
        ls -la bin/ || echo "No bin directory found"
        echo "Contents of buildozer directory:"
        find .buildozer -name "*.apk" -type f || echo "No APK files found in .buildozer"

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: ifmealplanner-apk
        path: |
          bin/*.apk
          .buildozer/android/platform/build-*/dists/*/bin/*.apk
        if-no-files-found: warn

    - name: Upload logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: buildozer-logs
        path: |
          .buildozer/android/platform/build-*/build.log
          .buildozer/logs/
          .buildozer/android/platform/build-*/dists/*/build.log
        if-no-files-found: ignore
