name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          unzip \
          wget \
          curl \
          autoconf \
          libtool \
          pkg-config \
          automake \
          cmake \
          gettext \
          libffi-dev \
          libssl-dev \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \
          libreadline-dev \
          libbz2-dev \
          libsqlite3-dev \
          tk-dev \
          libgdbm-dev \
          libdb-dev \
          libpcap-dev \
          xz-utils \
          libexpat1-dev \
          liblzma-dev \
          libgdbm-compat-dev \
          ccache

    - name: Install Java 8
      run: |
        sudo apt-get install -y openjdk-8-jdk
        export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
        echo "JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" >> $GITHUB_ENV

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        pip install buildozer==1.5.0
        pip install cython==0.29.33
        pip install colorama appdirs sh jinja2 six

    - name: Cache Buildozer global directory
      uses: actions/cache@v3
      with:
        path: .buildozer_global
        key: buildozer-global-${{ hashFiles('buildozer.spec') }}

    - name: Cache Buildozer directory  
      uses: actions/cache@v3
      with:
        path: .buildozer
        key: buildozer-${{ hashFiles('buildozer.spec', '**/*.py') }}

    - name: Clean any previous build
      run: |
        buildozer android clean || true

    - name: Build with Buildozer
      run: |
        buildozer -v android debug
      env:
        JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
        ANDROID_ACCEPT_SDK_LICENSE: y
        USE_CCACHE: 1
        CCACHE_DIR: ~/.ccache

    - name: List build output
      run: |
        echo "Contents of bin directory:"
        ls -la bin/ || echo "No bin directory found"
        echo "Contents of buildozer directory:"
        find .buildozer -name "*.apk" -type f || echo "No APK files found in .buildozer"

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: ifmealplanner-apk
        path: |
          bin/*.apk
          .buildozer/android/platform/build-*/dists/*/bin/*.apk
        if-no-files-found: warn

    - name: Upload logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: buildozer-logs
        path: |
          .buildozer/android/platform/build-*/build.log
          .buildozer/logs/
          .buildozer/android/platform/build-*/dists/*/build.log
        if-no-files-found: ignore
